version: "3.8"

services:
  app:
    # Build the image using the Dockerfile in the current directory
    build: .
    # Name the container for easier identification (optional)
    container_name: react-native-expo-dev
    # Map the ports exposed in the Dockerfile to the host machine
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "8081:8081" # Important for Metro bundler/debugger
    # Mount the current directory (.) on the host to /app in the container
    volumes:
      - .:/app
      # Add an anonymous volume for node_modules
      # This prevents the node_modules directory from your host machine
      # (which might have been created with a different OS/architecture)
      # from overwriting the one installed inside the container.
      # This is crucial for cross-platform consistency.
      - /app/node_modules
    # Keep stdin open, allowing interaction with the process (e.g., Metro prompts)
    stdin_open: true
    # Allocate a pseudo-TTY, necessary for interactive terminals
    tty: true
    # Environment variables to help with file watching inside the container,
    # especially when using Docker Desktop on macOS or Windows.
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true # Newer variable often used by Webpack/Metro
      # Set HOST to 0.0.0.0 to ensure the server binds correctly within the container
      - HOST=0.0.0.0
    # Optional: Uncomment if you need specific React Native debugger settings
    # environment:
    #   - REACT_NATIVE_PACKAGER_HOSTNAME=${DOCKER_HOST_IP:-host.docker.internal} # Tries to get host IP
